#!/bin/bash

# Quick setup - Run this after GitHub Actions secrets are configured

echo "🚀 GitHub Actions - Quick Deploy Checklist"
echo "=========================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Prerequisites${NC}"
echo "✓ GitHub repository created"
echo "✓ Azure account with active subscription"
echo "✓ Azure CLI installed"
echo "✓ GitHub CLI installed"
echo ""

echo -e "${BLUE}Step 1: Generate Credentials${NC}"
echo "----------------------------"
echo "Run: bash .github/setup-github-actions.sh"
echo ""

echo -e "${BLUE}Step 2: Verify Secrets${NC}"
echo "---------------------"
echo "Run: gh secret list"
echo ""
echo "Expected secrets:"
echo "  • AZURE_CREDENTIALS"
echo "  • AZURE_CLIENT_ID"
echo "  • AZURE_CLIENT_SECRET"
echo "  • AZURE_SUBSCRIPTION_ID"
echo "  • AZURE_TENANT_ID"
echo "  • AZURE_RESOURCE_GROUP"
echo "  • AZURE_STORAGE_ACCOUNT"
echo ""

echo -e "${BLUE}Step 3: Configure Terraform${NC}"
echo "-----------------------------"
echo "Edit: INFRA/terraform.tfvars"
echo "  • app_name: ai-reviewer"
echo "  • environment: dev"
echo "  • azure_region: eastus"
echo "  • Enable/disable features as needed"
echo ""

echo -e "${BLUE}Step 4: Deploy Infrastructure${NC}"
echo "------------------------------"
echo "Option A - Manual via CLI:"
echo "  cd INFRA"
echo "  terraform init -backend-config='...' # See GITHUB_ACTIONS_SETUP.md"
echo "  terraform plan"
echo "  terraform apply"
echo ""
echo "Option B - Via GitHub Actions:"
echo "  1. Push changes to INFRA/ to main"
echo "  2. Go to Actions tab"
echo "  3. Select 'Deploy Infrastructure with Terraform'"
echo "  4. Review plan output"
echo "  5. Manually trigger with action=apply"
echo ""

echo -e "${BLUE}Step 5: Update Environment Variables${NC}"
echo "-------------------------------------"
echo "After infrastructure is deployed:"
echo "  1. Get Azure App Service URLs"
echo "  2. Update GitHub secrets:"
echo "     - VITE_API_AUTH_URL"
echo "     - VITE_API_EDITOR_URL"
echo "     - VITE_API_AI_URL"
echo "     - VITE_API_REPO_FIXER_URL"
echo "     - VITE_API_CODE_GEN_URL"
echo "     - VITE_WS_EDITOR_URL"
echo "     - VITE_WS_AI_URL"
echo "     - VITE_FRONTEND_URL"
echo ""

echo -e "${BLUE}Step 6: Get Publish Profiles${NC}"
echo "----------------------------"
echo "For each Azure App Service:"
echo "  az webapp deployment list-publishing-profiles \\"
echo "    --resource-group YOUR_RG \\"
echo "    --name YOUR_APP_NAME"
echo ""
echo "Add as GitHub secrets:"
echo "  - AZURE_WEBAPP_AUTH_PUBLISH_PROFILE"
echo "  - AZURE_WEBAPP_EDITOR_PUBLISH_PROFILE"
echo "  - AZURE_WEBAPP_AI_PUBLISH_PROFILE"
echo "  - AZURE_WEBAPP_FIXER_PUBLISH_PROFILE"
echo "  - AZURE_WEBAPP_CODEGEN_PUBLISH_PROFILE"
echo "  - AZURE_WEBAPP_FRONTEND_PUBLISH_PROFILE"
echo ""

echo -e "${BLUE}Step 7: Test Workflows${NC}"
echo "---------------------"
echo "1. Test Job:"
echo "   - Push to develop branch"
echo "   - Verify test.yml runs"
echo "   - Check results in Actions tab"
echo ""
echo "2. Backend Deployment:"
echo "   - Push to main branch in AI_CODE_REVIEWER_BACKEND\ copy/services/"
echo "   - Verify deploy-backend.yml runs"
echo "   - Check Azure App Services for updates"
echo ""
echo "3. Frontend Deployment:"
echo "   - Push to main branch in AI_CODE_REVIEWER_FRONTED\ copy/app/"
echo "   - Verify deploy-frontend.yml runs"
echo "   - Check Azure App Service for updates"
echo ""

echo -e "${BLUE}Step 8: Monitor Deployments${NC}"
echo "----------------------------"
echo "GitHub Actions:"
echo "  - Go to repo → Actions tab"
echo "  - Select workflow"
echo "  - Monitor job progress and logs"
echo ""
echo "Azure Portal:"
echo "  - Check App Service deployment history"
echo "  - Review Application Insights logs"
echo "  - Monitor resource health"
echo ""

echo -e "${GREEN}✅ All Steps Documented!${NC}"
echo ""
echo -e "${YELLOW}Troubleshooting:${NC}"
echo "  • Check .github/GITHUB_ACTIONS_SETUP.md for detailed guide"
echo "  • Review workflow logs in GitHub Actions"
echo "  • Verify Azure credentials"
echo "  • Check resource quotas and limits"
echo ""
